var data = [
    {
        id: 1,
        name: '',
        age: '',
        condition: '',
        state: '',
    },
    {
        id: 2,
        name: '',
        age: '',
        condition: '',
        state: '',
    },
    {
        id: 3,
        name: '',
        age: '',
        condition: '',
        state: '',
    },
    {
        id: 4,
        name: '',
        age: '',
        condition: '',
        state: '',
    },
    {
        id: 5,
        name: '',
        age: '',
        condition: '',
        state: '',
    },
    {
        id: 6,
        name: '',
        age: '',
        condition: '',
        state: '',
    },
    {
        id: 7,
        name: '',
        age: '',
        condition: '',
        state: '',
    },
    {
        id: 8,
        name: '',
        age: '',
        condition: '',
        state: '',
    },
    {
        id: 9,
        name: '',
        age: '',
        condition: '',
        state: '',
    },
    {
        id: 10,
        name: '',
        age: '',
        condition: '',
        state: '',
    },
    {
        id: 11,
        name: '',
        age: '',
        condition: '',
        state: '',
    },
    {
        id: 12,
        name: '',
        age: '',
        condition: '',
        state: '',
    },
    {
        id: 13,
        name: '',
        age: '',
        condition: '',
        state: '',
    },
    {
        id: 14,
        name: '',
        age: '',
        condition: '',
        state: '',
    },
    {
        id: 15,
        name: '',
        age: '',
        condition: '',
        state: '',
    },
    {
        id: 16,
        name: '',
        age: '',
        condition: '',
        state: '',
    },
    {
        id: 17,
        name: '',
        age: '',
        condition: '',
        state: '',
    },
]